<h2>Edit the blog:</h2>

<?php echo $this->tag->form("addpost/editblog/$userid"); ?>
<?php echo $userid;?>

    <p>
        <label for="email">username:</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>
    <p>
        <label for="email">Title:</label>
        <?php echo $this->tag->textField("title"); ?>
    </p>
    <p>
        <label for="email">Content:</label>
        <?php echo $this->tag->textarea("content"); ?>
    </p>
   

    <p>
        <?php echo $this->tag->submitButton("Edit Post"); ?>
    </p>

</form>